# Generated by Django 3.0.7 on 2020-06-04 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=50, unique=True)),
                ('admin_password', models.CharField(default='666666', max_length=50, null=True)),
                ('admin_email', models.EmailField(max_length=254, null=True)),
                ('admin_phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(default=None, max_length=100)),
                ('blog_content', models.TextField(max_length=5120)),
                ('blog_lable', models.IntegerField()),
                ('blog_create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('blog_public_style', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0, null=True)),
                ('blog_like_count', models.IntegerField(default=0, null=True)),
                ('blog_comment_count', models.IntegerField(default=0, null=True)),
                ('blog_access_count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadPortrait',
            fields=[
                ('header_id', models.AutoField(primary_key=True, serialize=False)),
                ('header_path', models.FilePathField(path='\\home\\jiarui\\python-test\\django\\mysite\\blog\\image')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_id', models.AutoField(primary_key=True, serialize=False)),
                ('style_windows_color', models.CharField(default='white', max_length=10, null=True)),
                ('style_font_size', models.SmallIntegerField(default=12, null=True)),
                ('style_font_weight', models.SmallIntegerField(default=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=18, unique=True)),
                ('user_password', models.CharField(max_length=18)),
                ('user_email', models.EmailField(max_length=50, null=True)),
                ('user_phone', models.CharField(max_length=20, null=True)),
                ('user_nickname', models.CharField(default=models.CharField(max_length=18, unique=True), max_length=50)),
                ('user_sex', models.CharField(choices=[('男', 'nan'), ('女', 'nv')], default='男', max_length=2)),
                ('use_create_time', models.DateTimeField(auto_now_add=True)),
                ('user_update_time', models.DateTimeField(auto_now_add=True)),
                ('user_head_portrait', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='race.HeadPortrait')),
                ('user_style', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='race.Style')),
            ],
        ),
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('lable_id', models.AutoField(primary_key=True, serialize=False)),
                ('lable_content', models.CharField(max_length=50)),
                ('lable_blog_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='race.Blog')),
                ('lable_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='race.User')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friend_id', models.AutoField(primary_key=True, serialize=False)),
                ('friend_note', models.CharField(max_length=50)),
                ('friend_status', models.SmallIntegerField(choices=[(0, 0), (1, 1)])),
                ('friend_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_m', to='race.User')),
                ('friend_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_n', to='race.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_like_count', models.IntegerField(default=0, null=True)),
                ('comment_content', models.TextField(max_length=1024)),
                ('comment_blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.Blog')),
                ('comment_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.User')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.User'),
        ),
    ]
